config/routes.rb
Splashbox::Application.routes.draw do
  root "pages#marketing"

  get '/me', to: 'dashboard#index', as: :dashboard

  get '/waitlist' => redirect('/')

  match 'auth',     via: [:get, :post], to: 'dropbox#authorize', as: :auth
  match 'callback', via: [:get],  to: 'dropbox#authorized_callback', as: :callback

  get '/logout', to: 'dropbox#destroy', as: :logout
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Splashbox::Dropbox

  serialize :colors, Array

  attr_accessible :source_url,
                  :author_name,
                  :author_url,
                  :colors,
                  :quick_url

  def self.new_from_scraper source_url, quick_url, author_name, author_url
    Photo.create source_url: source_url, quick_url: quick_url, author_name: author_name, author_url: author_url
  end

  def save_to_dropbox user, id, url
    agent = Mechanize.new

    # Deal with any redirects (e.g. bit.ly)
    initial_url = agent.get(url)
    destination_url = initial_url.uri.to_s

    content = agent.get_file(destination_url)
    upload_file(user, "#{ id }.jpg", content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Splashbox::Dropbox

  after_create :get_dropbox_attributes

  serialize :completions, Array

  attr_accessible :name,
                  :email,
                  :dropbox_uid,
                  :access_token,
                  :access_secret,
                  :customer_id,
                  :completions,
                  :waitlist,
                  :disconnected

  scope :consumers,   -> { where(waitlist: false).where(disconnected: false) }
  scope :waiters,     -> { where(waitlist: true) }

  def consumer?
    not completions.empty?
  end

  private

  def get_dropbox_attributes
    set_name_and_email(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    begin
      @current_user ||= User.find session[:user_id] if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      nil
    end
  end

  def correct_user?
    begin
      @user = User.find(session[:user_id])
      unless current_user == @user
        flash[:alert]= "Tisk, tisk, you shouldn't try to access another person's data"
        redirect_to dashboard_path
      end
    rescue ActiveRecord::RecordNotFound
      flash[:alert]= "There's nothing over there"
      redirect_to dashboard_path
    end
  end

  def authenticate_user!
    if !current_user
      flash[:alert] = "You must authenticate first to view your dashboard."
      redirect_to root_url
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    customer = Stripe::Customer.create(
      card: params[:stripeToken],
      plan: 'basic',
      email: params[:email]
    )

    current_user.update_attributes! customer_id: customer.id, email: customer.email, waitlist: false
    redirect_to dashboard_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?
  before_filter :get_photos, only: :index

  def index
    @waiters = User.waiters.sort_by(&:created_at)
  end

  private

  def get_photos
    @photos = []
    current_user.completions.each do |source_url|
      if photo = Photo.find_by_source_url(source_url)
        @photos << photo
      end
    end

    @photos.sort!{ |a,b| b.created_at <=> a.created_at }
  end
end

app/controllers/dropbox_controller.rb
class DropboxController < ApplicationController

  def authorize
    consumer = Dropbox::API::OAuth.consumer(:authorize)
    request_token = consumer.get_request_token
    session[:request_token] = request_token.token
    session[:request_token_secret] = request_token.secret
    redirect_to request_token.authorize_url(oauth_callback: callback_url)
  end

  def authorized_callback
    consumer = Dropbox::API::OAuth.consumer(:authorize)
    request_token = OAuth::RequestToken.new(consumer, session[:request_token], session[:request_token_secret])
    if params[:not_approved] == "true"
      flash[:error] = "Oops! Looks like you didn't complete authentication with Dropbox."
      redirect_to root_url
    else
      result = request_token.get_access_token(oauth_verifier: params[:oauth_token])
      create_user_and_return_home(result)
    end
  end

  def create_user_and_return_home(result)
    if user = User.find_by_dropbox_uid(params[:uid])
      user.update_attributes(access_token: result.token, access_secret: result.secret)
      session[:user_id] = user.id

      if user.waitlist?
        flash[:notice] = "You're still on the waitlist. Please be patient :)"
      else
        flash[:notice] = "Welcome back :)"
      end
      redirect_to dashboard_path
    else
      user = User.create!(access_token: result.token, access_secret: result.secret, dropbox_uid: params[:uid])
      session[:user_id] = user.id

      flash[:notice] = "Beauty! Successfully connected Splashbox with Dropbox. You're now on the waitlist."
      redirect_to dashboard_path
    end
  end

  def destroy
    reset_session
    flash[:notice] = "Logged out. Come back soon!"
    redirect_to root_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :get_counts, only: :marketing

  def marketing
  end

  private

  def get_counts
    @user_count    = 0
    @photo_count   = 0
    @payload_count = Photo.count

    User.find_each do |u|
      if u.consumer?
        @user_count  += 1
        @photo_count += u.completions.length
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dashboard_primary_button
    link_to 'https://www.dropbox.com/home/Apps/Splashbox' do
      button_tag sanitize('View Photos &rarr;'), class: 'purple'
    end
  end

  def waitlist_spot
    hash = Hash[@waiters.map.with_index.to_a]
    hash[@user] + 1
  end
end

app/views/application/_flashes.html.erb
<div class="flash">
  <% flash.each do |key, value| -%>
    <p id="message" class="<%= key %>"><%= value %></p>
  <% end -%>
</div>

app/views/application/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="column full">
        <ul>
          <% if @user.present? %>
            <li><a href="<%= logout_path %>">Log out</a></li>
          <% else %>
            <li><a href="<%= auth_url %>">Get Started</a></li>
          <% end %>
        </ul>

        <p class="animated fadeInUp">
          <a href="http://heroku.com"><%= image_tag 'heroku-logo.svg', width: '124', height: '42' %></a>
          <a href="http://dropbox.com"><%= image_tag 'dropbox-logo.svg', width: '150', height: '42' %></a>
          <a href="http://embed.ly"><%= image_tag 'embedly-logo.svg', width: '129', height: '42' %></a>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/application/_panel.html.erb
<div class="sublist-panel" style="display:none;">
  <div class=" s-header">
    <div class="s-h3">Version 2.0</div>
    <div class="s-a close">&times;</div>
  </div>
  <div class="s-article">
    <ul>
      <li>
        <p>Color Palettes</p>
        <p>A color palette is now generated for every photo delivered to your Dropbox. You can view them through your dashboard.</p>
      </li>
      <li>
        <p>Donations <span id="stripe-outline"></span></p>
        <p>I've added the ability to make a $1 monthly donation through your dashboard.</p>
      </li>
    </ul>
  </div>
</div>

app/views/application/_photo_counter.html.erb
<section class="no-border" id="stats">
  <div class="container">
    <div class="row">
      <div class="column full">
        <h3 class="animated fadeInUpBig"><span class="dropbox-photo-count count odometer" data-count="<%= @photos.count %>"></span> hi-resolution photos have been added to your Dropbox</h3>
      </div>
    </div>
  </div>
</section>

app/views/application/_seen.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="column full">
        <ul class="seen animated fadeInDownBig">
          <li><a id="unsplash" href="http://365.unsplash.com" title="Unsplash"></a></li>
          <li><a id="product-hunt" href="http://www.producthunt.com/posts/splashbox" title="ProductHunt"></a></li>
          <li><a id="wefunction" href="http://wefunction.com/8-unique-places-to-find-quality-free-photos" title="WeFunction"></a></li>
          <li><a id="charged" href="http://us8.campaign-archive2.com/?u=7ba9643cb80dac69c6818848c&id=d7df6165a7" title="Charged"></a></li>
          <li><a id="uniiverse" href="http://blog.uniiverse.com/2014/07/31/3-simple-tips-design-eye-catching-event-flyer" title="Uniiverse"></a></li>
          <li><a id="bianca-board" href="http://blog.web123partners.com.au/blog/9-free-non-stock-photos-sites.aspx" title="BiancaBoard"></a></li>
          <li><a id="site-report-builder" href="http://www.sitebuilderreport.com/blog/where-the-best-designers-go-to-find-photos-and-graphics" title="SiteReportBuilder"></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/application/_testimonials.html.erb
<section id="testimonials">
  <div class="container">
    <div class="row">
      <div class="column full">
        <ul id="avatars">
          <li class="avatar active animated fadeIn" data-avatar="0">
            <%= image_tag 'avatar-1.png', width: '85', height: '85' %>
            <div class="bio">
              <p>Luke Chesser</p>
              <p>Product Designer, Crew Labs</p>
            </div>
          </li>
          <li class="avatar animated fadeIn" data-avatar="1">
            <%= image_tag 'avatar-2.png', width: '85', height: '85' %>
            <div class="bio">
              <p>Pete Heslop</p>
              <p>Director, BrightByte Studio</p>
            </div>
          </li>
          <li class="avatar animated fadeIn" data-avatar="2">
            <%= image_tag 'avatar-3.png', width: '85', height: '85' %>
            <div class="bio">
              <p>Matthew Smith</p>
              <p>Entrepreneur &amp; Designer</p>
            </div>
          </li>
          <li class="avatar animated fadeIn" data-avatar="3">
            <%= image_tag 'avatar-4.png', width: '85', height: '85' %>
            <div class="bio">
              <p>Owen Williams</p>
              <p>Journalist &amp; Developer</p>
            </div>
          </li>
        </ul>

        <h3 class="testimonial active animated fadeIn">I use Splashbox to store Unsplash photos locally. It makes it so easy to find and drop photos into any design. Splashbox also saves me a ton of time and gives me constant access to high-res photos, regardless of an internet connection.</h3>
        <h3 class="testimonial animated fadeIn">Splashbox allows us, as a small agency to deliver high quality stock images every time. We no longer have to search through fake, forced and expensive photography, we now have them delivered to our Dropbox. The seamless and simple integration with Dropbox means we never have to think again about our source of imagery.</h3>
        <h3 class="testimonial animated fadeIn">Splashbox has become a part of the innovative internet. Photographers get known and I get hundreds of visually interesting non-stock high-res photos at my disposal whenever I need them. Bonus.</h3>
        <h3 class="testimonial animated fadeIn">Splashbox delivers you the most beautiful wallpapers you can find online straight into your Dropbox. I dig having hundreds of wallpapers that automatically change on my Mac so I don't see the same thing every day, plus you can use them quickly when you need something for a project! I'll never go back.</h3>
      </div>
    </div>
  </div>
</section>

app/views/application/_waitlist.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="column half">
        <h2>Waitlist.</h2>
        <p>Your account should be activated shortly.</p>
      </div>
      <div class="column half animated fadeIn">
        <%= image_tag 'watch.svg', width: '295', height: '231' %>
      </div>
    </div>
  </div>
</section>

app/views/application/_waitlist_counter.html.erb
<section id="stats">
  <div class="container">
    <div class="row">
      <div class="column full">
        <h3 class="animated fadeInUpBig">You're number <span class="count"><%= waitlist_spot %></span> of <span class="waitlist-count count odometer" data-count="<%= @waiters.count %>"></span> users on the waitlist</h3>
      </div>
    </div>
  </div>
</section>

app/views/dashboard/_gallery.html.erb
<div id="grid-gallery" class="grid-gallery">
  <section class="grid-wrap">
    <ul class="grid">
      <li class="grid-sizer"></li>
      <% @photos.each do |photo| %>
        <li>
          <figure>
            <img class="lazy" data-original="<%= photo.quick_url %>" width="238" height="158" alt="img<%= photo.id %>"/>
          </figure>
        </li>
      <% end %>
    </ul>
  </section>
  <section class="slideshow">
    <ul>
      <% @photos.each do |photo| %>
        <li>
          <figure>
            <a href="<%= photo.source_url %>" target="_blank">
              <!-- TODO Load images faster -->
              <img src="<%= photo.quick_url %>" alt="img<%= photo.id %>"/>
            </a>
            <figcaption>
              <p>Photo by <a href="<%= photo.author_url %>" target="_blank"><%= photo.author_name %></a></p>
              <% photo.colors.each do |color| %>
                <div class="tooltip color-block" style="background:rgb(<%= color['color'][0] %>, <%= color['color'][1] %>, <%= color['color'][2] %>);" title="rgb(<%= color['color'][0] %>, <%= color['color'][1] %>, <%= color['color'][2] %>)"></div>
              <% end %>
            </figcaption>
          </figure>
        </li>
      <% end %>
    </ul>
    <nav>
      <span class="icon nav-prev" data-icon="&#59237;" data-aria="hidden"></span>
      <span class="icon nav-next" data-icon="&#59238;" data-aria="hidden"></span>
      <span class="icon nav-close" data-icon="&#10060;" data-aria="hidden"></span>
    </nav>
  </section>
</div>

app/views/dashboard/index.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="column full">
        <div class="overlay animated pulse"></div>
        <article class="animated fadeIn">
          <h1 id="logo">Splashbox</h1>
          <p>Hi-resolution photos delivered to your Dropbox</p>
            <%= dashboard_primary_button %>
        </article>
      </div>
    </div>
  </div>
</header>

<% if @user.waitlist? %>
  <%= render 'waitlist_counter' %>
  <%= render 'waitlist' %>
<% else %>
  <%= render 'photo_counter' %>
  <%= render 'gallery' %>
<% end %>

<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Splashbox</title>
  <%= stylesheet_link_tag :application, :media => 'all' %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>" id="<%= action_name %>">
  <%= render 'flashes' -%>
  <%= yield %>
</body>
</html>

app/views/pages/marketing.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="column full">
        <div class="overlay animated fadeIn"></div>
        <article class="animated fadeIn">
          <h1 id="logo">Splashbox</h1>
          <p>Hi-resolution photos delivered to your Dropbox</p>
          <small id="version">Version 1.0</small>
          <a class="button" href="<%= auth_url %>"><button class="purple">Get Started &rarr;</button></a>
        </article>
      </div>
    </div>
  </div>
</header>

<section id="stats">
  <div class="container">
    <div class="row">
      <div class="column full">
        <h3 class="animated fadeInUpBig"><span class="photo-count count odometer" data-count="<%= @photo_count %>"></span> photos delivered to over <span class="user-count count odometer" data-count="<%= @user_count %>"></span> Dropbox accounts</h3>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="column half">
        <h2>Connect Your Dropbox.</h2>
        <p>You'll need to <a href="<%= auth_url %>">authorize</a> your Dropbox account with us and provide access for us to push new photos to your account when they become available.</p>
        <a class="button" href="<%= auth_url %>"><button class="purple">Connect Now &rarr;</button></a>
      </div>
      <div class="column half animated fadeIn">
        <%= image_tag 'dropbox.svg', width: '213', height: '225' %>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="column half">
        <h2>Watch the Waitlist.</h2>
        <p>Due to current demand I've had to create a waitlist. Once you've connected your Dropbox account you'll be placed on the waitlist.</p>
        <p>Your spot on the waitlist can be seen in your dashboard.</p>
        <a class="button" href="<%= dashboard_path %>"><button class="purple">View Waitlist &rarr;</button></a>
      </div>
      <div class="column half animated fadeIn">
        <%= image_tag 'watch.svg', width: '295', height: '231' %>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="column half">
        <h2>Get Photos.</h2>
        <p>Once your account is activated, you will start seeing photos being delivered to your Dropbox.</p>
        <p>Your initial payload will include <span class="payload-count count odometer" data-count="<%= @payload_count %>"></span> photos curated by the <a href="http://unsplash.com">Unsplash</a> team. Thereafter, every 10 days or so you will automatically receive another set of 10 photos delivered to your Dropbox.</p>
        <p>You just sit back and relax.</p>
      </div>
      <div class="column half animated fadeIn">
        <%= image_tag 'computer.svg', width: '295', height: '386' %>
      </div>
    </div>
  </div>
</section>

<%= render 'footer' %>